name: flutter_maps
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  firebase_core: ^2.13.0
  firebase_messaging: ^14.6.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^14.0.0+2
  flutter_map: ^4.0.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  http: ^0.13.6
  latlong2: ^0.8.1
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
